### ISSUE TITLE
实现平面上的A*

### ISSUE THREAD

**Issue by mia0813** [Alexbeast-CN/3d-surface-planner#5]
实现在任意CostMap上点到点的A*路径规划。

- [x] ros2和Nav2环境搭建
- [x] A*实现（python）
- [x] A*双向搜索实现（python）

**Comment by mia0813** [comment]
换成了python来实现A*，实现了随机设置起点和目标点的双向搜索，效果很好。
![1709884352342](https://github.com/Alexbeast-CN/3d-surface-planner/assets/152155933/f20dfebe-bb39-4078-bd81-0c63eaa89197)

**Comment by Daoming-Chen** [comment]
> 换成了python来实现A*，实现了随机设置起点和目标点的双向搜索，效果很好。 

如果是双线程的就更好了
